name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..10}; do
            if mongosh --eval "db.adminCommand({ ping: 1 })" mongodb://localhost:27017/test; then
              echo "MongoDB is ready"
              exit 0
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done
          echo "MongoDB failed to start"
          exit 1

      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/test
        run: npm test -- --coverage --testTimeout=30000

      - name: List test result files
        run: ls -al ./coverage && ls -al ./reports/junit

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: './coverage/lcov-report'
          name: 'github-pages'

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4