name: Deploy coverage report to Pages

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_PORT: 3000
          file_name: .env
          fail_on_empty: true
          sort_keys: false
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test -- --testTimeout=30000
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4
      - name: Upload Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'coverage/lcov-report'
          name: 'github-pages'
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4